# Generated by Django 5.1.15 on 2026-09-04 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('metric_date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('watch_time', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('followers_gained', models.IntegerField(default=0)),
                ('raw_data_json', models.JSONField(default=dict)),
                ('is_demo_data', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='assets.generatedasset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='workspaces.workspace')),
            ],
        ),
    ]
