# Generated by Django 5.1.15 on 2026-09-04 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'X/Twitter'), ('blog', 'Blog'), ('shorts', 'Short-form Video')], max_length=50)),
                ('asset_type', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('metadata_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft / Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50)),
                ('current_version', models.IntegerField(default=1)),
                ('created_by_ai', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_assets', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('content', models.TextField()),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assets.generatedasset')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
    ]
