# Generated by Django 5.1.15 on 2026-09-04 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('text', 'Text Topic/Idea'), ('transcript', 'Raw Transcript'), ('video', 'Video File'), ('audio', 'Audio File'), ('document', 'Document (PDF/DOCX/TXT)'), ('url', 'Public URL Import')], default='text', max_length=50)),
                ('source_text', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploading', 'Uploading'), ('extracting', 'Extracting'), ('transcribing', 'Transcribing'), ('analysing', 'Analysing'), ('generating', 'Generating Assets'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('target_platforms', models.JSONField(default=list)),
                ('target_audience', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(default='English', max_length=50)),
                ('tone', models.CharField(default='Professional & Engaging', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(default='pipeline_all', max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('current_stage', models.CharField(default='Initializing', max_length=100)),
                ('provider', models.CharField(default='deterministic', max_length=100)),
                ('attempts', models.IntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('safe_error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='SourceAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=100)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_assets', to='campaigns.campaign')),
            ],
        ),
    ]
