import Link from 'next/link';
import { ArrowRight, CalendarDays, Check, FileText, Layers3, Search, Sparkles, WandSparkles } from 'lucide-react';

const features = [
  { icon: WandSparkles, title: 'Multi-platform generation', text: 'Turn one topic, transcript, or upload into tailored content for every major channel.' },
  { icon: Search, title: 'SEO quality checks', text: 'Score titles and copy, then apply focused recommendations immediately.' },
  { icon: CalendarDays, title: 'Publishing calendar', text: 'Approve assets and manage the complete publishing queue from one workspace.' },
];

export default function LandingPage() {
  return <main className="min-h-screen bg-white text-slate-900">
    <header className="sticky top-0 z-50 border-b border-slate-200 bg-white/95 backdrop-blur">
      <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8">
        <Link href="/" className="flex items-center gap-3" aria-label="Sabd Studio home"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary font-bold text-white">S</span><span className="font-semibold">Sabd Studio</span></Link>
        <nav className="hidden items-center gap-7 text-sm text-slate-600 md:flex"><a href="#features" className="hover:text-primary">Features</a><a href="#workflow" className="hover:text-primary">How it works</a><a href="#platforms" className="hover:text-primary">Platforms</a></nav>
        <div className="flex items-center gap-2"><Link href="/login" className="rounded-lg px-3 py-2 text-sm font-medium hover:bg-slate-100">Sign in</Link><Link href="/register" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Get started <ArrowRight className="h-4 w-4" /></Link></div>
      </div>
    </header>

    <section className="border-b border-slate-200 px-5 py-20 sm:px-8 sm:py-28">
      <div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2">
        <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-semibold text-primary"><Sparkles className="h-3.5 w-3.5" /> AI workspace for modern creators</div><h1 className="text-4xl font-bold leading-[1.08] tracking-tight sm:text-6xl">One idea. Every content channel. <span className="text-primary">Ready faster.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Sabd Studio converts source content into searchable, editable, and publish-ready assets—without juggling multiple tools.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/dashboard" className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-6 py-3.5 text-sm font-semibold text-white hover:bg-blue-700">Open live workspace <ArrowRight className="h-4 w-4" /></Link><Link href="/register" className="inline-flex items-center justify-center rounded-lg border border-slate-300 px-6 py-3.5 text-sm font-semibold hover:bg-slate-50">Create free account</Link></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-600">{['No card required', 'Editable AI drafts', 'Export-ready output'].map(item => <span key={item} className="flex items-center gap-2"><Check className="h-4 w-4 text-primary" />{item}</span>)}</div></div>
        <div className="rounded-2xl border border-slate-200 bg-white p-3 shadow-[0_20px_60px_rgba(15,23,42,.10)]"><div className="rounded-xl border border-slate-200 bg-slate-50 p-5"><div className="flex items-center justify-between border-b border-slate-200 pb-4"><div><p className="text-xs text-slate-500">Campaign workspace</p><p className="mt-1 font-semibold">Creator Workflow Launch</p></div><span className="rounded-full bg-blue-100 px-2.5 py-1 text-xs font-semibold text-primary">Complete</span></div><div className="mt-4 grid grid-cols-3 gap-3">{[['6','Assets'],['86','SEO score'],['4','Channels']].map(([v,l]) => <div key={l} className="rounded-lg border border-slate-200 bg-white p-3"><p className="text-xl font-bold">{v}</p><p className="text-xs text-slate-500">{l}</p></div>)}</div><div className="mt-4 space-y-2">{[[FileText,'YouTube description'],[Layers3,'LinkedIn carousel'],[Search,'SEO analysis']].map(([Icon,title]: any) => <div key={title} className="flex items-center gap-3 rounded-lg border border-slate-200 bg-white p-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue-50 text-primary"><Icon className="h-4 w-4" /></span><p className="flex-1 text-sm font-medium">{title}</p><ArrowRight className="h-4 w-4 text-slate-400" /></div>)}</div></div></div>
      </div>
    </section>

    <section id="features" className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold text-primary">Everything in one workflow</p><h2 className="mt-2 text-3xl font-bold">Less manual work. More consistent content.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{features.map(({icon:Icon,title,text}) => <article key={title} className="rounded-xl border border-slate-200 p-6 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-lg bg-blue-50 text-primary"><Icon className="h-5 w-5" /></span><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

    <section id="workflow" className="border-y border-slate-200 bg-slate-50 px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-center text-3xl font-bold">From source to schedule in three steps</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[['01','Add your source','Start with a topic, transcript, document, audio, or video.'],['02','Generate a campaign','Create channel-specific drafts and metadata.'],['03','Review and publish','Edit, approve, schedule, or export your content.']].map(([n,t,d]) => <div key={n} className="rounded-xl border border-slate-200 bg-white p-6"><span className="text-sm font-bold text-primary">{n}</span><h3 className="mt-4 font-semibold">{t}</h3><p className="mt-2 text-sm text-slate-600">{d}</p></div>)}</div></div></section>
    <section id="platforms" className="px-5 py-16 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 rounded-2xl bg-primary px-7 py-10 text-white md:flex-row"><div><h2 className="text-2xl font-bold">Ready to build your next campaign?</h2><p className="mt-2 text-sm text-blue-100">Create once, then adapt for YouTube, Instagram, LinkedIn, X, blogs, and Shorts.</p></div><Link href="/dashboard/campaigns/new" className="shrink-0 rounded-lg bg-white px-5 py-3 text-sm font-semibold text-primary hover:bg-blue-50">Create campaign</Link></div></section>
    <footer className="border-t border-slate-200 px-5 py-8 text-sm text-slate-500 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 sm:flex-row"><p>© 2026 Sabd Studio. Creator workflow automation.</p><div className="flex gap-6"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><a href="https://github.com/chandan326/sabd-studio" target="_blank" rel="noreferrer">GitHub</a></div></div></footer>
  </main>;
}
