'use client';
import { Play, RotateCcw, Scissors } from 'lucide-react';
const bars=[32,48,70,44,78,55,88,62,45,76,92,58,80,40,68,84,52,72,94,60,78,48,66,86,54,74,90,46,70,56,82,64,42,76,88,58,72,50,84,62];
const clock=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
type Props={duration:number;start:number;end:number;onChange:(start:number,end:number)=>void;onPreview:()=>void;disabled?:boolean;compact?:boolean};
export default function TrimTimeline({duration,start,end,onChange,onPreview,disabled=false,compact=false}:Props){
 const total=Math.max(1,duration),selected=Math.max(0,end-start);
 const preset=(kind:string)=>{if(kind==='full')onChange(0,total);if(kind==='first15')onChange(0,Math.min(15,total));if(kind==='last15')onChange(Math.max(0,total-15),total);if(kind==='center30'){const length=Math.min(30,total),from=Math.max(0,(total-length)/2);onChange(Math.round(from),Math.round(from+length));}};
 const updateStart=(value:number)=>{if(Number.isFinite(value))onChange(Math.max(0,Math.min(value,end-.1)),end)};
 const updateEnd=(value:number)=>{if(Number.isFinite(value))onChange(start,Math.min(total,Math.max(value,start+.1)))};
 return <section className={`rounded-2xl border border-slate-200 bg-white shadow-sm ${compact?'p-4':'p-5'}`}><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 text-sm font-bold"><Scissors className="h-4 w-4 text-primary"/>Smart Trim</h2><p className="mt-0.5 text-[11px] text-muted-foreground">Drag the handles to keep exactly the section you need.</p></div><div className="flex items-center gap-2"><span className="rounded-lg bg-blue-50 px-2.5 py-1.5 text-xs font-bold text-primary">{clock(start)}–{clock(end)}</span><button disabled={disabled} onClick={onPreview} className="inline-flex items-center gap-1.5 rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-white disabled:opacity-40"><Play className="h-3.5 w-3.5"/>Preview</button></div></div>
 <div className={`${compact?'mt-3 px-3 py-3':'mt-5 px-4 py-5'} rounded-xl border border-slate-200 bg-slate-950`}><div className={`relative ${compact?'h-11':'h-16'}`}><div className={`absolute inset-x-0 flex items-center justify-between gap-1 overflow-hidden ${compact?'top-1 h-8':'top-2 h-11'}`}>{bars.map((height,index)=><span key={index} className="w-full rounded-full bg-blue-400" style={{height:`${height}%`,opacity:index/bars.length<start/total||index/bars.length>end/total?.2:1}}/>)}</div><div className={`pointer-events-none absolute top-0 border-x-2 border-primary bg-primary/15 ${compact?'h-11':'h-16'}`} style={{left:`${start/total*100}%`,width:`${selected/total*100}%`}}/><input aria-label="Trim start" className={`trim-range absolute inset-x-0 z-10 w-full ${compact?'top-3':'top-5'}`} type="range" min="0" max={total} step="0.1" value={start} onChange={e=>updateStart(Number(e.target.value))}/><input aria-label="Trim end" className={`trim-range absolute inset-x-0 z-20 w-full ${compact?'top-3':'top-5'}`} type="range" min="0" max={total} step="0.1" value={end} onChange={e=>updateEnd(Number(e.target.value))}/></div><div className={`${compact?'mt-1':'mt-2'} flex justify-between text-[10px] text-slate-300`}><span>{clock(0)}</span><span>Selected {clock(selected)}</span><span>{clock(total)}</span></div></div>
 <div className={`${compact?'mt-3':'mt-4'} flex flex-col gap-3 xl:flex-row xl:items-end xl:justify-between`}><div className="flex flex-wrap gap-1.5">{[['full','Full'],['first15','First 15s'],['last15','Last 15s'],['center30','Best 30s']].map(([id,label])=><button key={id} disabled={disabled} onClick={()=>preset(id)} className="rounded-lg border px-2.5 py-1.5 text-[10px] font-semibold hover:bg-blue-50 disabled:opacity-40">{label}</button>)}<button aria-label="Reset trim" disabled={disabled} onClick={()=>preset('full')} title="Reset trim" className="rounded-lg border p-1.5 disabled:opacity-40"><RotateCcw className="h-3.5 w-3.5"/></button></div><div className="grid grid-cols-2 gap-2"><label className="text-[9px] font-semibold text-slate-500">START<input aria-label="Trim start seconds" disabled={disabled} type="number" min="0" max={end-.1} step="0.1" value={Number(start.toFixed(1))} onChange={e=>updateStart(Number(e.target.value))} className="mt-1 block w-full rounded-lg border px-2 py-1.5 text-xs text-slate-900 xl:w-20"/></label><label className="text-[9px] font-semibold text-slate-500">END<input aria-label="Trim end seconds" disabled={disabled} type="number" min={start+.1} max={total} step="0.1" value={Number(end.toFixed(1))} onChange={e=>updateEnd(Number(e.target.value))} className="mt-1 block w-full rounded-lg border px-2 py-1.5 text-xs text-slate-900 xl:w-20"/></label></div></div></section>;
}
