'use client';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api } from '@/lib/api';
import { ArrowRight, CheckCircle2, Clapperboard, Link2, Sparkles, Upload, WandSparkles } from 'lucide-react';

const getYoutubeId=(value:string)=>{try{const url=new URL(value);if(url.hostname.includes('youtu.be'))return url.pathname.slice(1);if(url.hostname.includes('youtube.com'))return url.searchParams.get('v')||url.pathname.split('/').filter(Boolean).pop()||'';}catch{}return ''};
const stamp=(seconds:number)=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;

export default function ClipStudioPage(){
 const router=useRouter(); const [url,setUrl]=useState(''); const [duration,setDuration]=useState(300); const [type,setType]=useState('shorts'); const [transcript,setTranscript]=useState(''); const [sourceFileName,setSourceFileName]=useState(''); const [highlights,setHighlights]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const videoId=useMemo(()=>getYoutubeId(url),[url]);
 const analyse=async()=>{if(!videoId&&!transcript.trim()){setMessage('Add a valid YouTube link or transcript first.');return}setLoading(true);setMessage('Analysing hooks, information density, and standalone value…');try{const data=await api.analyseHighlights({source_url:url,transcript,duration,clip_type:type});setHighlights(data.highlights||[]);setMessage(`${data.highlights?.length||0} highlight suggestions ready.`)}catch(error:any){setMessage(error.message||'Analysis failed.')}finally{setLoading(false)}};
 const edit=(clip:any)=>{localStorage.setItem('sabd_clip_handoff',JSON.stringify({start:clip.start,end:clip.end,aspect:type==='vlog'?'16:9':'9:16',caption:clip.hook,clipType:type,title:clip.title}));router.push('/dashboard/media')};
 return <div className="space-y-6"><div className="flex flex-col gap-4 border-b border-border pb-5 lg:flex-row lg:items-end lg:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1 text-[11px] font-bold text-primary"><Sparkles className="h-3.5 w-3.5"/>AI highlight detection</span><h1 className="mt-3 text-2xl font-bold">AI Clip Studio</h1><p className="mt-1 max-w-2xl text-xs leading-5 text-muted-foreground">Find high-potential moments, then turn your own long-form video into Shorts, Reels, or vlog cuts.</p></div><div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-[11px] text-amber-900">Use only content you own or are authorised to edit.</div></div>
 <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="aspect-video overflow-hidden rounded-xl bg-slate-950">{videoId?<iframe key={videoId} className="h-full w-full" src={`https://www.youtube.com/embed/${videoId}`} title="YouTube source preview" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:<div className="grid h-full place-items-center text-center text-white"><div><Clapperboard className="mx-auto h-10 w-10 text-blue-400"/><p className="mt-3 text-sm font-semibold">Paste a YouTube link to preview</p><p className="mt-1 text-xs text-slate-400">The source remains embedded from YouTube.</p></div></div>}</div><div className="mt-4 rounded-xl border border-dashed border-blue-200 bg-blue-50/50 p-4"><label className="flex cursor-pointer items-center justify-between gap-3 text-xs"><span className="flex items-center gap-2 font-semibold"><Upload className="h-4 w-4 text-primary"/>{sourceFileName||'Upload your original for cutting'}</span><input type="file" accept="video/*" onChange={event=>{const file=event.target.files?.[0];setSourceFileName(file?.name||'');if(file)setMessage(`${file.name} selected. Choose a suggested clip, then load the original in Media Editor to render.`)}} className="max-w-52 text-[10px] file:rounded-md file:border-0 file:bg-primary file:px-3 file:py-2 file:text-white"/></label></div></section>
 <aside className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><label className="block text-xs font-semibold"><span className="flex items-center gap-2"><Link2 className="h-4 w-4 text-primary"/>YouTube link</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://youtube.com/watch?v=…" className="mt-2 w-full rounded-lg border px-3 py-2.5 text-xs"/></label><div><p className="text-xs font-semibold">Create format</p><div className="mt-2 grid grid-cols-3 gap-2">{[['shorts','Short'],['reel','Reel'],['vlog','Vlog']].map(([id,label])=><button key={id} onClick={()=>setType(id)} className={`rounded-lg border px-2 py-2 text-xs font-semibold ${type===id?'border-primary bg-blue-50 text-primary':''}`}>{label}</button>)}</div></div><label className="block text-xs font-semibold">Video duration (seconds)<input type="number" min="30" max="14400" value={duration} onChange={e=>setDuration(Number(e.target.value))} className="mt-2 w-full rounded-lg border px-3 py-2 text-xs"/></label><label className="block text-xs font-semibold">Transcript <span className="font-normal text-muted-foreground">(best AI results)</span><textarea rows={6} value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="Paste your own transcript or captions here…" className="mt-2 w-full rounded-lg border px-3 py-2 text-xs leading-5"/></label><button disabled={loading} onClick={analyse} className="flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-3 text-xs font-bold text-white disabled:opacity-50"><WandSparkles className="h-4 w-4"/>{loading?'Finding highlights…':'Find best moments'}</button><p role="status" className="text-[11px] leading-4 text-muted-foreground">{message}</p></aside></div>
 {highlights.length?<section className="space-y-4"><div><h2 className="text-lg font-bold">Recommended clips</h2><p className="text-xs text-muted-foreground">Ranked by hook strength, context, information density, and standalone value.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{highlights.map((clip,index)=><article key={clip.id||index} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="relative aspect-[9/12] bg-gradient-to-b from-slate-800 to-slate-950 p-5 text-white"><div className="flex justify-between"><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] font-bold">CLIP {String(index+1).padStart(2,'0')}</span><span className="rounded-full bg-emerald-400 px-2 py-1 text-[10px] font-black text-emerald-950">{clip.score}% match</span></div><div className="absolute inset-x-5 bottom-5"><p className="text-lg font-bold leading-tight">{clip.hook}</p><p className="mt-2 text-xs text-slate-300">{stamp(clip.start)} – {stamp(clip.end)}</p></div></div><div className="p-4"><div className="flex items-start gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary"/><div><h3 className="text-sm font-bold">{clip.title}</h3><p className="mt-1 text-[11px] text-muted-foreground">{clip.reason}</p></div></div><button onClick={()=>edit(clip)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg border border-primary px-3 py-2.5 text-xs font-bold text-primary hover:bg-blue-50">Edit this clip <ArrowRight className="h-3.5 w-3.5"/></button></div></article>)}</div></section>:null}
 </div>;
}
