# Generated by Django 5.1.15 on 2026-09-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformintegration',
            name='provider',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram / Meta'), ('linkedin', 'LinkedIn'), ('twitter', 'X / Twitter'), ('cloudinary', 'Cloudinary'), ('mongodb', 'MongoDB'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('whisper', 'Whisper'), ('elevenlabs', 'ElevenLabs'), ('gmail', 'Gmail SMTP')], max_length=50),
        ),
    ]
