# Generated by Django 5.1.15 on 2026-09-04 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(default='My Creator Brand', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('audience', models.CharField(default='General Tech & Business Creators', max_length=255)),
                ('niche', models.CharField(default='Technology / Education', max_length=255)),
                ('language', models.CharField(default='English', max_length=50)),
                ('tone', models.CharField(default='Authoritative yet conversational and engaging', max_length=100)),
                ('preferred_terms', models.TextField(blank=True, default='actionable, step-by-step, framework, breakdown')),
                ('avoided_terms', models.TextField(blank=True, default='synergy, revolutionary, cheap hacks')),
                ('content_goals', models.TextField(blank=True, default='Drive engagement, educate audience, build brand trust')),
                ('sample_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to='workspaces.workspace')),
            ],
        ),
    ]
